[build]
  command = "npm run build --workspace=apps/web"
  publish = "apps/web/.next"


[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/next/**", "node_modules/styled-jsx/**"]
